# Generated by Django 4.1.5 on 2023-01-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='order_data',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_detail', models.CharField(max_length=100, null=True)),
                ('order_date', models.DateField(null=True)),
                ('order_address', models.CharField(max_length=200, null=True)),
                ('order_tel', models.CharField(max_length=11, null=True)),
                ('order_username', models.CharField(max_length=100, null=True)),
                ('order_email', models.EmailField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='order_detail',
            fields=[
                ('detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_id', models.CharField(max_length=10, null=True)),
                ('p_qty', models.IntegerField(null=True)),
                ('p_price', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='product_data',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100, null=True)),
                ('product_qty', models.IntegerField(null=True)),
                ('product_price', models.IntegerField(null=True)),
                ('product_detail', models.TextField(null=True)),
            ],
        ),
    ]
