# Generated by Django 4.1.5 on 2023-01-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.CharField(max_length=100, null=True)),
                ('product_qty', models.IntegerField(null=True)),
                ('product_price', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
            ],
        ),
    ]
