# Generated by Django 4.1.5 on 2023-02-04 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_cart_cart_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_add',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product_data'),
        ),
        migrations.AlterField(
            model_name='order_data',
            name='order_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.order_detail'),
        ),
        migrations.AlterField(
            model_name='order_detail',
            name='p_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product_data'),
        ),
    ]
