# Generated by Django 4.1.5 on 2023-02-05 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_order_data_order_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_detail',
            name='p_id',
        ),
        migrations.AddField(
            model_name='order_detail',
            name='p_id',
            field=models.ManyToManyField(null=True, to='product.product_data'),
        ),
    ]
