# Generated by Django 4.1.5 on 2023-02-05 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_order_detail_p_id_order_detail_p_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_detail',
            name='p_id',
        ),
        migrations.AddField(
            model_name='order_detail',
            name='p_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product_data'),
        ),
    ]
