# Generated by Django 4.1.5 on 2023-02-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_order_detail_p_id_order_detail_p_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_detail',
            name='detail_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
